# Generated by Django 5.0.1 on 2024-02-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='phonenumber',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectMembershipPlan',
            new_name='SelectMembershipplan',
        ),
    ]
